### ISSUE TITLE
Suggestion: Dependency bundles

### ISSUE THREAD

**Issue by ddevault** [vigoo/bari#105]
This:

```
- name: Bari.Core.Test
  references:
    - gac://Microsoft.CSharp
    - gac://System
    - gac://System.Core
    - gac://System.Data
    - gac://System.Data.DataSetExtensions
    - gac://System.Xml
    - gac://System.Xml.Linq
    - nuget://FluentAssertions/2.2.0
    - nuget://Moq
    - alias://ninject
    - nuget://NUnit
    - nuget://YamlDotNet.Core
    - nuget://YamlDotNet.RepresentationModel
    - module://Bari.Core
- name: bari.Test
  references:
    - gac://System
    - gac://System.Xml
    - gac://System.Xml.Linq
    - nuget://log4net
    - alias://ninject
    - nuget://FluentAssertions/2.2.0
    - nuget://Moq
    - nuget://NUnit
    - module://Bari.Core
    - module://bari
```

Could be this:

```
- bundle: tests
    - gac://Microsoft.CSharp
    - gac://System
    - gac://System.Core
    - gac://System.Xml
    - gac://System.Xml.Linq
    - nuget://FluentAssertions/2.2.0
    - nuget://Moq
    - nuget://log4net
    - alias://ninject
    - nuget://NUnit
    - nuget://YamlDotNet.Core
    - nuget://YamlDotNet.RepresentationModel
# ...
- name: Bari.Core.Test
  references:
    - bundle://tests
    - module://Bari.Core
    - gac://System.Data
    - gac://System.Data.DataSetExtensions
- name: bari.Test
  references:
    - bundle://tests
    - module://Bari.Core
    - module://bari
```
