### ISSUE TITLE
Module and suite level C#/F#/C++ compiler and linker parameter blocks

### ISSUE THREAD

**Issue by Psychobilly87** [vigoo/bari#145]

**Comment by vigoo** [comment]
Unfortunately this is not documented (yet), but:

```yaml
csharp:
    target-framework: 4.0-client
```

or

```yaml
csharp:
    target-framework-version: 4.0
    target-framework-profile: client
```

See [here](https://github.com/vigoo/bari/blob/5d1c076bbc3f6092add0bd95f5ac63704adbe4f0/src/dotnetplugins/Bari.Plugins.Csharp/cs/Model/Loader/CsharpParametersLoader.cs#L61-L63)
