### ISSUE TITLE
ability to specify startup executable module for product

### ISSUE THREAD

**Issue by zvrana** [vigoo/bari#68]
example:

```
products:
  - name: prod1
    startup: mod2
    modules:
      - mod1
      - mod2
      - mod3
```
