### ISSUE TITLE
Better error detection in suite yaml

### ISSUE THREAD

**Issue by vigoo** [vigoo/bari#72]
Notify the user if instead of

``` yaml
cpp-compiler:
    defines:
       - X
       - Y
```

the YAML contains

``` yaml
cpp-compiler:
    - defines:
       - X
       - Y
```
