### ISSUE TITLE
Ability to negating goals

### ISSUE THREAD

**Issue by p5ych08illy** [vigoo/bari#89]
For example:

``` yaml
goals:
    - name: viewer

...

 defines:
       - when not viewer:
               -NVIEWER
```
