### ISSUE TITLE
Wrong sln name 

### ISSUE THREAD

**Issue by p5ych08illy** [vigoo/bari#90]
If there is only one module in the product the solution file name is wrong.

With this suite.yaml:

``` yaml

---
suite:      Test
version:    3.1.0.8
#contracts:  enabled


goals:
    - name: debug-x86
      incorporates:
          - debug
          - x86
    - name: debug-x64
      incorporates:
          - debug
          - x64
    - name: release-x86
      incorporates:
          - release
          - x86
    - name: release-x64
      incorporates:
          - release
          - x64

aliases:
    clrbase:
        - gac://System
        - gac://System.Core
        - gac://System.Xml
        - gac://Microsoft.Csharp
    wpf:
        - gac://System.Xaml
        - gac://PresentationCore
        - gac://PresentationFramework
        - gac://WindowsBase
        - gac://WindowsFormsIntegration
    winforms:
        - gac://System.Drawing
        - gac://System.Windows.Forms


modules:
    - name: SmartPResultViewer
      projects:
          - name: SmartPViewer
            type: windows-executable
            csharp:
               when x86:
                  platform: x86
               when x64:
                  platform: x64
            references:
                - alias://clrbase
                - alias://wpf
                - alias://winforms

products:
    - name: spv
      modules:
        - SmartPResultViewer

```

bari --target debug-x86 build spv

Generated sln:
Module_SmartPResultViewer.SmartPViewer.sln
